###########################################
#  Minio Setup
###########################################

version: "3.8"

volumes:
  datalake:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=192.168.1.100,nolock,soft,rw"
      device: ":/mnt/promox/data/datalake-data"

services:

  # Minio Storage Server
  minio:
    image: minio/minio:RELEASE.2023-07-21T21-12-44Z
    container_name: minio
    environment:
      - MINIO_ROOT_PASSWORD=/run/secrets/MINIO_ROOT_PASSWORD
      - MINIO_CONFIG_ENV_FILE=/etc/config.env
    volumes:
      - datalake:/minio/data/
      - /var/lib/docker-data/minio/config.env:/etc/config.env
    secrets:
      - MINIO_ROOT_PASSWORD
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "--console-address", ":9001"]
